apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::753270080777:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build      \n- groups:\n  - system:bootstrappers\n  - system:nodes\n
    \ rolearn: arn:aws:iam::753270080777:role/eksctl-eksctl-demo-nodegroup-ng-60-NodeInstanceRole-Y3ABPhWreSzC\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-20T12:50:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "40406"
  uid: 9e6f7ee3-15d3-4f9e-881d-f2f7f001af5d
