apiVersion: v1
data:
  mapRoles: "- groups:\n  - system:masters\n  rolearn: arn:aws:iam::753270080777:role/UdacityFlaskDeployCBKubectlRole\n
    \ username: build  \n- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn:
    arn:aws:iam::753270080777:role/eksctl-eksctl-demo-nodegroup-ng-18-NodeInstanceRole-UvRXFcWRj3Mp\n
    \ username: system:node:{{EC2PrivateDNSName}}\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-19T18:04:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4476"
  uid: ce85916c-4dbd-4e3f-bb63-fed7e9f49519
